from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class ExplanationType(str, Enum):
    RISK = "RISK"
    MIGRATION = "MIGRATION"
    READINESS = "READINESS"
    ROADMAP = "ROADMAP"


class Explanation(BaseModel):
    """
    Domain model representing a deterministic, auditable explanation for a
    specific decision, score, or recommendation generated by AgileGraph.
    """

    explanation_id: UUID = Field(default_factory=uuid4)
    asset_id: Optional[UUID] = None
    explanation_type: ExplanationType
    title: str
    explanation: str
    supporting_evidence: List[str]
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
