import json
import os
import sys
from pathlib import Path

def main():
    res_path = Path("research/results.json")
    stats_path = Path("research/statistical_results.json")
    preds_path = Path("research/predictions.json")
    
    if not res_path.exists() or not stats_path.exists() or not preds_path.exists():
        print("Missing JSON outputs. Run experiments and statistics first.")
        return
        
    with open(res_path, "r") as f:
        results = json.load(f)
        
    with open(stats_path, "r") as f:
        stats = json.load(f)
        
    with open(preds_path, "r") as f:
        preds = json.load(f)
        
    # Calculate Cohens Kappa using sklearn (as the existing service might be complex to import standalone)
    from sklearn.metrics import cohen_kappa_score
    kappas = {}
    
    y_true = preds["Full Model"]["y_true"]
    
    for model_name, data in preds.items():
        if "y_pred" in data:
            kappa = cohen_kappa_score(y_true, data["y_pred"])
            kappas[model_name] = kappa
            
    # Regenerate dataset-validation.md
    dataset_md = f"""# Dataset Validation

## Corpus Specifications
- **Total Repositories**: 40
- **Cross-Validation**: 5-Fold Repo-level splits
- **Labeling Scheme**: Binary (`PQC-Safe` vs `Legacy-Vulnerable`) deterministically derived from AST primitive matching (e.g. RSA, ECDSA -> Vulnerable).
- **Internal Validation**: Each fold holds out 15% of its training repos for early-stopping validation to prevent data leakage.

*Note: The original 10-repository corpus was found to be statistically degenerate. The 40-repo dataset ensures that single-repo anomalies cannot drag the F1 score to 0.*
"""
    with open("research/dataset-validation.md", "w") as f:
        f.write(dataset_md)
        
    # Regenerate statistical-analysis.md
    
    table_rows = []
    
    for model, f1_data in results["ablation_f1"].items():
        if isinstance(f1_data, dict):
            mean_f1 = f1_data["mean"]
            std_f1 = f1_data["std"]
            f1_str = f"{mean_f1:.3f} ± {std_f1:.3f}"
        else:
            f1_str = f"{f1_data:.3f}"
            
        kappa = kappas.get(model, 0.0)
        table_rows.append(f"| {model} | {f1_str} | {kappa:.3f} |")
        
    if "CBOMkit Baseline" in preds:
        cbom_kappa = kappas.get("CBOMkit Baseline", 0.0)
        # We don't have folds for CBOMkit so no std deviation easily, but we have bootstrap stats.
        # We will just write its kappa.
        table_rows.append(f"| CBOMkit Baseline | N/A (See Benchmark) | {cbom_kappa:.3f} |")
        
    stats_md = f"""# Statistical Analysis

## Agreement & F1 Stability (5-Fold CV)

| Model Variant | Macro-F1 (Mean ± Std) | Cohen's Kappa |
|---|---|---|
""" + "\n".join(table_rows) + """

## McNemar's Tests (Significance against Full Model)

"""
    mcnemar = stats.get("mcnemar", {})
    if "full_vs_noise" in mcnemar:
        p = mcnemar['full_vs_noise']['pvalue']
        stats_md += f"- **Full Model vs Random Noise (- CodeBERT)**: p = {p:.4e}\n"
    if "full_vs_het" in mcnemar:
        p = mcnemar['full_vs_het']['pvalue']
        stats_md += f"- **Full Model vs Homogeneous GCN (- Heterogeneous)**: p = {p:.4e}\n"
    if "full_vs_cbom" in mcnemar:
        p = mcnemar['full_vs_cbom']['pvalue']
        stats_md += f"- **Full Model vs CBOMkit Baseline**: p = {p:.4e}\n"
        
    stats_md += "\n*This document is auto-generated by `scripts/generate_statistical_report.py` to prevent metrics drift.*\n"

    with open("research/statistical-analysis.md", "w") as f:
        f.write(stats_md)
        
    print("Regenerated research/dataset-validation.md and research/statistical-analysis.md successfully!")

if __name__ == "__main__":
    main()
