import json
import os
from report_helpers import load_and_validate_sources

def main():
    res_path = "research/results.json"
    stats_path = "research/statistical_results.json"
    preds_path = "research/predictions.json"
    
    if not os.path.exists(res_path) or not os.path.exists(stats_path) or not os.path.exists(preds_path):
        print("Missing JSON outputs. Run experiments and statistics first.")
        return
        
    results, stats = load_and_validate_sources(res_path, stats_path)
        
    with open(preds_path, "r") as f:
        preds = json.load(f)
        
    # kappas are now calculated properly in statistical_tests.py
    kappas = {}
    kappa_stats = stats.get("kappa", {})
    for m, d in kappa_stats.items():
        kappas[m] = d.get("score", 0.0)
            
    # Regenerate dataset-validation.md
    dataset_md = """# Dataset Validation
    
    ## Corpus Specifications
    - **Total Repositories**: 40
    - **Cross-Validation**: 5-Fold Repo-level splits
    - **Labeling Scheme**: Binary (`PQC-Safe` vs `Legacy-Vulnerable`) deterministically derived from AST primitive matching (e.g. RSA, ECDSA -> Vulnerable).
    - **Internal Validation**: Each fold holds out 15% of its training repos for early-stopping validation to prevent data leakage.
    
    *Note: The original 10-repository corpus was found to be statistically degenerate. The 40-repo dataset ensures that single-repo anomalies cannot drag the F1 score to 0.*
    """
    with open("research/dataset-validation.md", "w", encoding="utf-8") as f:
        f.write(dataset_md)
        
    # Regenerate statistical-analysis.md
    
    table_rows = []
    
    for model, f1_data in results["ablation_f1"].items():
        if isinstance(f1_data, dict):
            mean_f1 = f1_data["mean"]
            std_f1 = f1_data["std"]
            f1_str = f"{mean_f1:.3f} \u00B1 {std_f1:.3f}"
        else:
            f1_str = f"{f1_data:.3f}"
            
        # Helper to format kappa safely
        def format_kappa(k):
            return f"{k:.3f}" if isinstance(k, float) else str(k)
            
        kappa = kappas.get(model, 0.0)
        table_rows.append(f"| {model} | {f1_str} (raw) | {format_kappa(kappa)} |")
        
    # Also include models that might only be in preds (like baselines)
    for model in preds.keys():
        if model not in results.get("ablation_f1", {}):
            if "CBOMkit Baseline" in model:
                kappa = kappas.get(model, 0.0)
                table_rows.append(f"| {model} | N/A (See Benchmark) | {format_kappa(kappa)} |")
            elif "Majority Class Baseline" in model:
                kappa = kappas.get(model, 0.0)
                # Compute majority class F1 dynamically
                y_true = preds[model]["y_true"]
                y_pred = preds[model]["y_pred"]
                from sklearn.metrics import f1_score
                f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)
                table_rows.append(f"| {model} | {f1:.3f} (raw) | {format_kappa(kappa)} |")
        
    stats_md = """# Statistical Analysis

## Agreement & F1 Stability (5-Fold CV)

Values below are the raw, unresampled mean across the 5 cross-validation folds — see `research/METRIC_CONVENTIONS.md` for why this differs from the bootstrapped headline figure used elsewhere.

| Model Variant | Macro-F1 (Raw 5-Fold Mean \u00B1 Std) | Cohen's Kappa |
|---|---|---|
""" + "\n".join(table_rows) + """

## McNemar's Tests (Significance against Full Model)

"""
    mcnemar = stats.get("mcnemar", {})
    if "full_vs_noise" in mcnemar:
        p = mcnemar['full_vs_noise']['pvalue']
        stats_md += f"- **Full Model vs Random Noise (- CodeBERT)**: p = {p:.4e}\n"
    if "full_vs_het" in mcnemar:
        p = mcnemar['full_vs_het']['pvalue']
        stats_md += f"- **Full Model vs Homogeneous GCN (- Heterogeneous)**: p = {p:.4e}\n"
    if "CBOMkit Baseline" in mcnemar:
        p = mcnemar["CBOMkit Baseline"]["p_value"]
        p_str = f"{p:.4e}" if isinstance(p, float) else str(p)
        stats_md += f"- **Full Model vs CBOMkit Baseline**: p = {p_str}\n"
        
    stats_md += "\n*This document is auto-generated by `scripts/generate_statistical_report.py` to prevent metrics drift.*\n"

    with open("research/statistical-analysis.md", "w", encoding="utf-8") as f:
        f.write(stats_md)
        
    print("Regenerated research/dataset-validation.md and research/statistical-analysis.md successfully!")

if __name__ == "__main__":
    main()
